### ISSUE TITLE
prettier breaks jinja whitespace control

### ISSUE THREAD

**Issue by MrWeeble** [davidodenwald/prettier-plugin-jinja-template#10]
Firstly, thanks for this, its made me able to get my jinja templates looking nice

I have a element which has a long enough class declaration such that the whole thing e.g
```
<element class="extemely_long__class_name extemely_long__class_name--modifier>{{ some_variable }}</element>
```
won't fit on on one line. Prettier therefore reformats it to (leaving out the class for clarity)
```
<element>
    {{ some_variable }}
</element>
```
Unfortunately as I am using a `white-space: pre` rule on that element this has undesirable side effects, by adding blank likes above and below the text

The way to fix that in jinja is to use the whitespace control rule and do
```
<element>
    {{- some_variable -}}
</element>
```

however this gets reformatted to
```
<element>
    {{ - some_variable - }}
</element>
```
which jinja parses as a syntax error

I've worked around it by adding `<!-- prettier-ignore -->` before the element, but wanted to let you know about the issue

**Comment by davidodenwald** [comment]
Sorry for the late response.

I didn't know that you could strip whitespace with a minus sign in an expression.

Support for this syntax has now been added with the [v0.3.0](https://www.npmjs.com/package/prettier-plugin-jinja-template/v/0.3.0) release.

If you consider whitespace significant in your templates you can also add the config option `"htmlWhitespaceSensitivity": "strict"` to you prettier config.
