### ISSUE TITLE
Project needs updating to Prettier v3.0

### ISSUE THREAD

**Issue by danielburnley** [davidodenwald/prettier-plugin-jinja-template#15]
Currently this depends on Prettier `^2.0.0` which is creating conflicts when trying to update other packages

As far as I can tell this needs two changes:

1. Update plugin test to handle format returning a `Promise<String>` now
2. Update the `embed` method to match the [new API](https://prettier.io/docs/en/plugins.html#optional-embed)

**Comment by davidodenwald** [comment]
I updated the plugin to support prettier v3 with the release of [v1.0.0](https://github.com/davidodenwald/prettier-plugin-jinja-template/releases/tag/v1.0.0)
