### ISSUE TITLE
Can't see any effects of plugin

### ISSUE THREAD

**Issue by pySilver** [davidodenwald/prettier-plugin-jinja-template#23]
I feel that I'm doing something wrong here :)

I have a sample test file called `products.html`

```jinja
{% extends "base.jinja2" %}

{% if href in ['layout.html', 'index.html, 'about.html', 'user.html'] %}
<h1>{{title}}</h1>
 {%elif href == "random.html" %}
<h2>{{title}}</h2>
{%else%}
<h3>{{title}}</h3>
{% endif %}
```

I'm running the following command:
```
prettier ./templates/catalog/product.html --write --plugin=prettier-plugin-jinja-template --plugin=prettier-plugin-tailwindcss
```

And well nothing happens to the file contents. Confusing :/

**Comment by davidodenwald** [comment]
This is because this plugin doesn't format `.html` files by default. You can define a override in your config (see README) or rename your file to `products.jinja`.

**Comment by pySilver** [comment]
@davidodenwald I've tried many options and by default my files have .jinja2 extension

**Comment by pySilver** [comment]
Silly me. It was on prettierignore due to alternative formatter.
