### ISSUE TITLE
Notice about new JinjaX syntax allowing the removal of the `quoteAttributes` config variable

### ISSUE THREAD

**Issue by JakobGM** [davidodenwald/prettier-plugin-jinja-template#33]
Hi, @davidodenwald :wave:

Almost a year ago you were kind enough to respond to my request in #17 for supporting the [JinjaX](https://github.com/jpsca/jinjax) flavor of Jinja2-templates. That work introduced a new `--no-quote-attributes` CLI flag and `quoteAttributes: <bool>` API override.

I just wanted to let you know that version `v0.4` of JinjaX got [released](https://github.com/jpsca/jinjax/releases/tag/0.4) two days ago where the syntax for passing variables into components changed from `attr_name={attr_vaue}` to `:attr_name="attr_value"`, and I'm happy to report that this plugin handles this syntax with no problems whatsoever, regardless of `quoteAttributes`.

You might therefore want to consider removing the `quoteAttributes` functionality altogether if you want to reduce the complexity of the plugin. Depending on your views of backwards compatibility, users will still be able to use the old plugin version if they are temporarily stuck on an old JinjaX version.

Thanks again,
- Jakob

**Comment by davidodenwald** [comment]
Hey Jakob,

Thanks for letting me know :+1: 
The branch removing the option is linked and will be published with the next major release.
