### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by 3w36zj6** [davidodenwald/prettier-plugin-jinja-template#38]
Thank you for creating and maintaining this project.

In the process of attempting to add functionality to this project or publish it as a separate project for the support of a similar but different language, I noticed the following. The `package.json` specifies `"license": "MIT"`, but there is no LICENSE file in this repository.

Could you possibly add a license file for clarification of the license?

**Comment by davidodenwald** [comment]
Hey, thanks for the suggestion. I added the license file.
