### ISSUE TITLE
Syntax error with `{{ ... }}` expression inside `<script>` tag

### ISSUE THREAD

**Issue by robertknight** [davidodenwald/prettier-plugin-jinja-template#5]
Formatting a template with a `{{ ... }}` Jinja expression inside a `<script>` tag results in a SyntaxError exception.

Example input:

```jinja2
{% if frontend_settings %}
<script class="js-app-settings" type="application/json">
{{ frontend_settings | to_json }}
</script>
{% endif %}
```

Output:

```
.../settings.html.jinja2
[error] .../settings.html.jinja2: SyntaxError: Unexpected token (2:2)
[error]   1 |
[error] > 2 | {{ frontend_settings | to_json }}
[error]     |  ^
[error]   3 |
```

If the `{{ frontend_settings | to_json }}` tag is moved outside of the `<script>` tag, the error does not occur.

Thanks for this plugin!

**Comment by davidodenwald** [comment]
Hey,
this plugin does not format inside script tags. In this case the json formatter tries to format the code and that's where the error message is coming from.
The simplest solution is to tell prettier to ignore the block:
```jinja
{% if frontend_settings %}
  <!-- prettier-ignore -->
  <script class="js-app-settings" type="application/json">
    {{ frontend_settings | to_json }}
  </script>
{% endif %}
```

**Comment by robertknight** [comment]
Thanks for the explanation. This solves my problem. It would be great if there was some reasonable way this could handled automatically, or with a more obvious error, though I'm not sure what that would look like.
